
class InstaComment{
 static List<String> instagramComments = [
    "Love it 😍",
    "So cute 🥰",
    "Wow 🔥",
    "Nice shot 📸",
    "Amazing 😍",
    "So cool 😎",
    "Beautiful ❤️",
    "Awesome 🔥",
    "Lovely 🥹",
    "Fantastic 🤗",
    "Pretty 💖",
    "Cool pic 📷",
    "So sweet 🐣",
    "Adorable 🥰",
    "Insane 🔥",
    "Wow vibes ✨",
    "Charming 💫",
    "Epic 😎",
    "Heartwarming ❤️",
    "Superb 😍",
    "Stunning 🌸",
    "Aesthetic 💕",
    "Brilliant 🤩",
    "Nice vibes 🌟",
    "Magical ✨",
    "Pure joy 🥹",
    "Fabulous 😍",
    "Dreamy 💖",
    "Love vibes ❤️",
    "This is absolutely beautiful ❤️✨",
    "Your vibe is unmatched 😍🔥",
    "Such a wholesome moment 🥹",
    "This made my day 🥰",
    "Every detail looks perfect 💫",
    "You’re glowing here 😍",
    "Such pure happiness ❤️",
    "This looks magical ✨",
    "Loving the colors here 🎨",
    "You have the best energy 🌟",
    "This is so heartwarming 🥹",
    "Everything about this is wow 🔥",
    "The vibes are unreal 😎",
    "Absolutely stunning shot 📸",
    "Your smile says it all ❤️",
    "This photo feels so alive 🌸",
    "Such positive energy 💖",
    "This is art 🎨✨",
    "Totally obsessed with this 😍",
    "Brings back good memories 🥰",
    "Your style is amazing 😎",
    "Such a calming scene 🌿",
    "You always inspire 💫",
    "This is pure love ❤️",
    "Perfectly captured moment 📷",
    "The happiness is contagious 😍",
    "This is too cute 🥹",
    "A vibe I want 🌟",
    "Such elegance here 💖",
    "Can’t stop looking at this ✨",
    "This picture radiates so much positivity and joy, it’s honestly impossible not to smile while looking at it ❤️🥰",
    "You have such a special way of capturing beauty in the simplest things, this is truly magical ✨📸",
    "I love how natural and authentic this feels, it’s like a moment frozen in pure happiness 💫🌸",
    "This is the kind of content that makes social media worth it — full of warmth and good vibes 🥹❤️",
    "The way the colors and your expression match here is absolutely perfect 😍🔥",
    "It’s so rare to see a post that feels this genuine and heartfelt, but you nailed it 💖✨",
    "Your photos always tell a story, and this one feels like a chapter full of love and happiness 📖❤️",
    "I swear every time you post, it’s just pure inspiration and positive energy 🌟🥰",
    "This is so beautiful that I actually had to stop scrolling just to appreciate it 😍📷",
    "The vibes here are absolutely unmatched — so cozy, warm, and uplifting 🌸✨",
    "You’ve captured a perfect mix of beauty and emotion, it’s simply breathtaking 💫❤️",
    "Every time I see your posts, I instantly feel happier — you’re a ray of sunshine ☀️🥹",
    "There’s something so special about this moment, like it was meant to be remembered forever 📸💖",
    "I can feel the love and positivity radiating from this photo, it’s amazing 😍🌟",
    "This looks like it belongs in a magazine, absolutely picture-perfect 😎🔥",
    "The happiness here is so real you can almost feel it through the screen 🥰❤️",
    "I love how effortlessly beautiful and natural you look here 💫✨",
    "You always manage to make even simple moments feel extraordinary 🌸💖",
    "This is pure art, from the lighting to the emotion — just wow 🎨😍",
    "I’m genuinely obsessed with how perfect this turned out, everything is on point 🌟🔥",
    "This is the kind of happiness everyone should experience at least once 🥹❤️",
    "The details here are so stunning, it’s like a dream captured in reality 💫🌸",
    "This gave me instant good vibes and made me smile today 😍🌟",
    "Your posts always remind me of the beauty in little things ❤️✨",
    "This is more than just a photo — it’s a feeling, and it’s amazing 💖📸",
    "Absolutely love the colors, the mood, and everything about this shot 😎🔥",
    "This feels like the start of a beautiful story 🥰📖",
    "The combination of elegance and joy here is perfect 🌸💫",
    "I hope you keep sharing moments like this, they’re truly inspiring ❤️✨",
    "This will forever be one of my favorite posts from you 😍📷",
  ];

  static String getInstaComment() {
    return (instagramComments..shuffle()).first;
  }
}