import 'dart:math';

class CommentList {
  static final List<String> comments = [
    // Short comments
    "Loved it!",
    "So helpful!",
    "Great job!",
    "Well explained!",
    "Nice work!",
    "Much needed!",
    "Super video!",
    "Amazing bro!",
    "Thanks a ton!",
    "So clear!",
    "Excellent!",
    "🔥🔥🔥",
    "Perfect video!",
    "Respect 🙌",
    "Instant like!",
    "Impressive!",
    "Just wow!",
    "Nailed it!",

    // Medium comments
    "This helped me understand the topic better!",
    "Awesome explanation. Subscribed right away!",
    "Simple, clean, and very effective content.",
    "You made it so easy to follow. Thank you!",
    "I wish I found this video earlier!",
    "This video deserves more attention!",
    "You explained this like a pro.",
    "Exactly what I was looking for!",
    "Truly appreciate the clarity in this.",
    "So much value in under 5 minutes.",
    "Best part of my day! Great content.",
    "The way you broke it down = perfect.",
    "Thank you! This saved me a lot of time.",
    "I really liked your presentation style.",
    "Finally, someone explained it properly!",
    "Super helpful and well structured.",
    "I enjoyed every second of this.",
    "Really appreciate this type of content.",
    "Keep posting videos like this!",
    "You've got a new fan here.",
    "I learned something new today. Thanks!",
    "That was way easier than I expected!",
    "Clear, helpful, and to the point.",
    "You make it all look so effortless.",
    "I'm sharing this with my friends!",
    "Please keep uploading more like this.",
    "This is YouTube gold right here.",
    "You just gained a subscriber!",
    "Every second was worth it.",
    "This was short but extremely valuable.",

    // Long comments
    "I can’t believe how clear and well-paced this video is. You really made a complex topic feel so simple. Major respect!",
    "The editing, the pacing, the delivery—everything was on point. This is how tutorials should be done!",
    "I’ve been struggling with this for days, and your video just solved it in minutes. You’re a lifesaver. Subscribed immediately!",
    "This kind of effort doesn’t go unnoticed. You clearly care about quality, and it shows in every second.",
    "I seriously don’t understand why this channel doesn’t have millions of subscribers already. Keep doing what you do!",
    "I just binge-watched three of your videos back-to-back. Your content is addictive and genuinely helpful.",
    "The calm tone, clear visuals, and structured explanation made this such an enjoyable learning experience.",
    "Everything from the thumbnail to the closing statement was professional and engaging. Amazing job!",
    "You really know how to engage the audience without making it feel forced. Respect for that natural delivery!",
    "Not just helpful—your video actually made the learning process fun. That’s rare these days!",
    "I love how you explain things like you're talking to a friend. It doesn’t feel robotic or scripted at all.",
    "This is the most beginner-friendly content I’ve seen so far. Thank you for taking the time to make this.",
    "I paused and rewatched several parts just to admire how smoothly you transitioned through the steps. Top-notch!",
    "I've been jumping from video to video, but this one actually gave me clarity. Thank you for standing out!",
    "There’s a calm confidence in your voice that makes me trust everything you say. Keep up this awesome work!",
    "Honestly, I was just browsing, but your content hooked me. Subscribed and turned on the bell!",
    "Your passion for what you do really comes through. I felt like you wanted me to succeed. That’s powerful.",
    "The effort you put into scripting and editing clearly sets you apart from the rest.",
    "I usually skip around in videos, but yours held my attention from start to finish. That says a lot!",
    "The way you explain is so intuitive, it’s like you know what I’m thinking before I even ask the question.",
    "I sent this to my little brother too—he’s just starting and this video is perfect for beginners.",
    "I rarely comment, but this video absolutely deserved it. Please keep making content like this!",
    "Every time I see a new upload from you, I know I’m about to learn something valuable. Never disappointed!",
    "Subscribed within 30 seconds of watching—this is the kind of content that restores my faith in YouTube.",
    "You clearly have a gift for teaching. Your calm and confident style makes all the difference.",
    "I genuinely felt more confident after watching this. That’s the mark of a great creator.",
    "This wasn’t just informative—it was motivating. Thank you for helping me stay on track.",
    "Your content deserves way more reach. Sharing this everywhere I can!",
    "I’ve watched similar videos, but none of them explained it as clearly and kindly as you did.",
    "If YouTube had a quality badge system, your video would be gold standard. Keep shining!"
  ];

  static String getRandomComment() {
    return (comments..shuffle()).first;
  }
}
